name: python test

on: [push]

jobs:
  python-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-schema

      - name: test test.py
        run: ./test.py

      - name: pytest test.py
        run: pytest test.py --verbose

      - name: 'pytest *.py'
        run: pytest $(git ls-files '*.py') --verbose

      - name: test main.py
        run: ./main.py

      - name: verify generated files are up-to-date
        run: |
          curl -X GET --location --output jtd-codegen.zip https://github.com/jsontypedef/json-typedef-codegen/releases/download/v0.4.1/x86_64-unknown-linux-musl.zip
          unzip jtd-codegen.zip
          chmod +x jtd-codegen
          ls ./python/typedef
          mkdir /tmp/typedef
          ./jtd-codegen --python-out /tmp/typedef --root-name senzingapi senzingapi-RFC8927.json
          ls /tmp/typedef
          diff ./python/typedef/__init__.py  /tmp/typedef/__init__.py
